Add YouTube Plus download and validation steps

diff --git a/.github/workflows/_build_tweaks.yml b/.github/workflows/_build_tweaks.yml
--- a/.github/workflows/_build_tweaks.yml
+++ b/.github/workflows/_build_tweaks.yml
@@ -111,6 +111,17 @@ jobs:
           deb_url="https://github.com/Mark02-2012/YTPlusM-DIY-5.2.1/releases/download/YTPlusVersions/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
           wget "$deb_url" --no-verbose -O ytplus.deb
 
+      - name: Download YouTube Plus (by URL)
+        if: ${{ inputs.tweak_url != '' }}
+        run: |
+          wget "${{ inputs.tweak_url }}" --no-verbose -O ytplus.deb
+          file_type=$(file --mime-type -b ytplus.deb)
+          if [[ "$file_type" != "application/vnd.debian.binary-package" ]]; then
+            echo "::error::Validation failed: The file is not a valid DEB file. Detected type: $file_type."
+            exit 1
+          fi
+   
+
       - name: Clone YouTubeHeader
         if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM }}
         run: |
@@ -180,6 +191,20 @@ jobs:
       - name: Clone YTLowContrastMode
         if: ${{ inputs.enable_YTLCM }}
         run: git clone --quiet --depth=1 https://github.com/arichornlover/YTLowContrastMode.git
+
+      - name: Patch YTLowContrastMode
+        if: ${{ inputs.enable_YTLCM }}
+        run: |
+         cd YTLowContrastMode
+          echo '#import <UIKit/UIKit.h>' > patch.txt
+          echo '#define IS_ENABLED(k) YES' >> patch.txt
+          echo '@interface YTQTMButton : UIButton' >> patch.txt
+          echo '- (void)setTintColor:(id)color;' >> patch.txt
+          echo '@end' >> patch.txt
+          echo '@interface YTCollectionViewCell : UICollectionViewCell' >> patch.txt
+          echo '@end' >> patch.txt
+          cat Tweak.xm >> patch.txt
+          mv patch.txt Tweak.xm
         
       - name: Build YouPiP
         if: ${{ inputs.enable_youpip }}
@@ -206,7 +231,7 @@ jobs:
           mv packages/*.deb ../ytabc.deb
 
       - name: Build YouGroupSettings
-        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_demc }}
+        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_demc || inputs.enable_YTLCM }}
         run: |
           cd YouGroupSettings && make clean package DEBUG=0 FINALPACKAGE=1
           mv packages/*.deb ../ygs.deb
@@ -218,7 +243,7 @@ jobs:
           mv packages/*.deb ../yq.deb
 
       - name: Build YTVideoOverlay
-        if: ${{ inputs.enable_yq || inputs.enable_youpip || inputs.enable_youspeed || inputs.enable_ytuhd }}
+        if: ${{ inputs.enable_yq || inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_youspeed }}
         run: |
           cd YTVideoOverlay && make clean package DEBUG=0 FINALPACKAGE=1
           mv packages/*.deb ../ytvo.deb
